import prisma from '../lib/prisma.js'
import { createNotification } from './notificationService.js'

export interface DigestData {
  weekStart: string
  weekEnd: string
  tasksCompleted: number
  user1Name: string
  user1Balance: number
  user2Name: string
  user2Balance: number
  achievementsUnlocked: string[]
  dailyStreakDays: number
}

/**
 * Sends weekly in-app digest notifications to all users in all couples.
 * Iterates every couple, computes last week's stats, and creates a
 * 'weekly_digest' Notification for each user in the couple.
 *
 * TODO (v2.1): Add email delivery here once email provider is integrated.
 * Each user already has `notificationsEmail` and `notificationPreferences`
 * fields that can gate email sending per user preference.
 */
export async function sendWeeklyDigests(): Promise<void> {
  const now = new Date()
  const { weekStart, weekEnd } = lastIsoWeekRange(now)

  const couples = await prisma.couple.findMany({
    include: {
      users: {
        select: { id: true, name: true },
      },
    },
  })

  for (const couple of couples) {
    if (couple.users.length === 0) continue

    try {
      const digest = await buildDigest(couple, weekStart, weekEnd)

      for (const user of couple.users) {
        await createNotification({
          coupleId: couple.id,
          userId: user.id,
          type: 'weekly_digest',
          title: `Resumen semanal: ${digest.tasksCompleted} tareas · ${digest.dailyStreakDays} días de racha`,
          message: JSON.stringify(digest),
        })
      }
    } catch (err) {
      console.error(`[digestService] Error building digest for couple ${couple.id}:`, err)
    }
  }
}

async function buildDigest(
  couple: { id: string; users: { id: string; name: string }[]; dailyStreakDays: number },
  weekStart: Date,
  weekEnd: Date
): Promise<DigestData> {
  const [user1, user2] = couple.users

  // Tasks completed last week (manual only — isAutoGenerated=false, status verified or pending)
  const tasksCompleted = await prisma.taskLog.count({
    where: {
      coupleId: couple.id,
      isAutoGenerated: false,
      status: { in: ['verified', 'pending'] },
      date: { gte: weekStart, lte: weekEnd },
    },
  })

  // Points balances per user (all-time running sum)
  const user1Balance = await getUserBalance(couple.id, user1?.id)
  const user2Balance = await getUserBalance(couple.id, user2?.id)

  // Achievements unlocked last week (UserAchievement + Achievement.name)
  const userIds = couple.users.map((u) => u.id)
  const unlockedThisWeek = await prisma.userAchievement.findMany({
    where: {
      userId: { in: userIds },
      unlockedAt: { gte: weekStart, lte: weekEnd },
    },
    include: {
      achievement: { select: { name: true } },
    },
  })
  const achievementsUnlocked = unlockedThisWeek.map((ua) => ua.achievement.name)

  // dailyStreakDays is on the Couple model (added v1.2)
  const dailyStreakDays = couple.dailyStreakDays ?? 0

  return {
    weekStart: weekStart.toISOString(),
    weekEnd: weekEnd.toISOString(),
    tasksCompleted,
    user1Name: user1?.name ?? '',
    user1Balance,
    user2Name: user2?.name ?? '',
    user2Balance,
    achievementsUnlocked,
    dailyStreakDays,
  }
}

async function getUserBalance(coupleId: string, userId: string | undefined): Promise<number> {
  if (!userId) return 0

  const result = await prisma.pointsTransaction.aggregate({
    where: { coupleId, userId },
    _sum: { amount: true },
  })

  return Number(result._sum.amount ?? 0)
}

/**
 * v2.5.1 audit 02 S1 — fix weekEnd boundary.
 *
 * Antes: `weekEnd.setDate(now.getDate() - now.getDay())` con `setHours(23,59,59)`.
 * Si el cron se ejecutaba un día que no fuera lunes (cold start delay,
 * test manual), la lógica producía solapamientos o agujeros con el digest
 * de la semana anterior.
 *
 * Ahora: helper canónico ISO week. Lunes 00:00 a Domingo 23:59:59 *de la
 * semana ANTERIOR* a `now`, sin importar qué día sea now.
 */
export function lastIsoWeekRange(now: Date): { weekStart: Date; weekEnd: Date } {
  const day = now.getUTCDay() // 0=Sun, 1=Mon, ..., 6=Sat
  // Días desde el último lunes (sin contar hoy si hoy es lunes).
  // Si day=1 (Mon), hace 7 días fue el lunes anterior.
  // Si day=0 (Sun), hace 6 días fue el lunes (mismo "esta semana"
  //                hasta domingo 23:59 — usar week previa).
  const daysSinceLastMonday = day === 0 ? 13 : day === 1 ? 7 : day - 1 + 7
  const weekStart = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() - daysSinceLastMonday, 0, 0, 0, 0),
  )
  const weekEnd = new Date(weekStart.getTime() + 7 * 24 * 60 * 60 * 1000 - 1)
  return { weekStart, weekEnd }
}
