import prisma from '../lib/prisma.js'
import type { Task } from '@prisma/client'

type Frequency = 'daily' | 'biweekly' | 'weekly' | 'bimonthly' | 'monthly'

interface OccurrenceOptions {
  maxCount?: number
  endDate?: Date
}

/**
 * Pure function: given a start date and frequency, returns the next N occurrence dates.
 * Exported for testing. Does NOT touch the database.
 */
export function getNextOccurrences(
  start: Date,
  frequency: Frequency,
  weeks: number,
  options: OccurrenceOptions = {}
): Date[] {
  const results: Date[] = []
  // When endDate is not provided, use a far-future sentinel so maxCount drives the limit.
  // When neither endDate nor maxCount is provided, weeks is used as the occurrence count.
  const endDate = options.endDate ?? new Date(8640000000000000) // max date sentinel
  const maxCount = options.maxCount ?? (options.endDate ? Infinity : weeks)
  let current = new Date(start)

  while (current <= endDate && results.length < maxCount) {
    results.push(new Date(current))
    switch (frequency) {
      case 'daily':
        current = new Date(current.getTime() + 86400000)
        break
      case 'biweekly':
        current = new Date(current.getTime() + 2 * 86400000)
        break
      case 'weekly':
        current = new Date(current.getTime() + 7 * 86400000)
        break
      case 'bimonthly':
        current = new Date(current.getTime() + 14 * 86400000)
        break
      case 'monthly': {
        const next = new Date(current)
        next.setMonth(next.getMonth() + 1)
        current = next
        break
      }
    }
  }

  return results
}

/**
 * Generate TaskLog instances (isAutoGenerated=true) for a recurring task
 * for the next 2 weeks (reducido desde 8 en 2026-04-22: con 8 semanas un daily
 * creaba 56 placeholders que saturaban las pestañas y complicaban el "anular
 * futuras" del panel Recurrentes; con 2 semanas el cron semanal renueva antes
 * de que se agoten y el usuario ve bastante horizonte sin abrumarse).
 * Skips dates that already have an auto-generated log.
 */
export async function generateOnCreate(task: Task): Promise<void> {
  if (!task.isRecurring || !task.frequency || !task.recurrenceStart) return

  const start = task.recurrenceStart
  const windowEnd = new Date(Date.now() + 2 * 7 * 86400000)
  const options: OccurrenceOptions = {
    endDate: task.recurrenceEnd
      ? new Date(Math.min(task.recurrenceEnd.getTime(), windowEnd.getTime()))
      : windowEnd,
  }
  if (task.maxOccurrences) {
    const remaining = task.maxOccurrences - task.occurrenceCount
    if (remaining <= 0) return
    options.maxCount = remaining
  }

  const dates = getNextOccurrences(start, task.frequency as Frequency, 8, options)
  if (dates.length === 0) return

  // Fetch existing auto-generated logs to avoid duplicates
  const existingLogs = await prisma.taskLog.findMany({
    where: { taskId: task.id, isAutoGenerated: true },
    select: { scheduledFor: true },
  })
  const existingDates = new Set(
    existingLogs
      .map(l => l.scheduledFor?.toISOString())
      .filter((d): d is string => d !== undefined)
  )

  const toCreate = dates.filter(d => !existingDates.has(d.toISOString()))
  if (toCreate.length === 0) return

  await prisma.$transaction([
    prisma.taskLog.createMany({
      data: toCreate.map(d => ({
        coupleId: task.coupleId,
        taskId: task.id,
        date: d,
        scheduledFor: d,
        isAutoGenerated: true,
        pointsBase: task.pointsBase,
        pointsFinal: task.pointsBase,
        status: 'pending',
      })),
      skipDuplicates: true,
    }),
    prisma.task.update({
      where: { id: task.id },
      data: { occurrenceCount: { increment: toCreate.length } },
    }),
  ])
}

/**
 * Extend the sliding window by one week for all recurring tasks of a couple.
 * Called by the Monday cron job.
 */
export async function generateInstancesForCouple(coupleId: string): Promise<void> {
  const tasks = await prisma.task.findMany({
    where: { coupleId, isRecurring: true, frequency: { not: null } },
  })
  for (const task of tasks) {
    await generateOnCreate(task)
  }
}

/**
 * Run weekly generation for ALL couples with active recurring tasks.
 * Called by cron every Monday at 08:00.
 */
export async function runWeeklyGeneration(): Promise<void> {
  const couples = await prisma.couple.findMany({
    where: { tasks: { some: { isRecurring: true } } },
    select: { id: true },
  })
  for (const couple of couples) {
    await generateInstancesForCouple(couple.id).catch(err =>
      console.error(`recurringTaskService error for couple ${couple.id}:`, err)
    )
  }
}
