import prisma from '../lib/prisma.js'
import { logger } from '../lib/logger.js'
import type { Prisma, Task } from '@prisma/client'

type Frequency = 'daily' | 'biweekly' | 'weekly' | 'bimonthly' | 'monthly'

interface OccurrenceOptions {
  maxCount?: number
  endDate?: Date
}

/**
 * Pure function: given a start date and frequency, returns the next N occurrence dates.
 * Exported for testing. Does NOT touch the database.
 */
export function getNextOccurrences(
  start: Date,
  frequency: Frequency,
  weeks: number,
  options: OccurrenceOptions = {}
): Date[] {
  const results: Date[] = []
  // When endDate is not provided, use a far-future sentinel so maxCount drives the limit.
  // When neither endDate nor maxCount is provided, weeks is used as the occurrence count.
  const endDate = options.endDate ?? new Date(8640000000000000) // max date sentinel
  const maxCount = options.maxCount ?? (options.endDate ? Infinity : weeks)
  let current = new Date(start)

  // v2.7.2 audit 02 S2-9 — clamp anchor-based para MONTHLY igual que
  // recurrenceService.advance (RFC 5545 §3.3.10). `setMonth(+1)` con
  // `current` el 31 de enero produce 3 de marzo (overflow). Usamos
  // anchorDay = el día original (31) y clampeamos al último día del
  // mes destino cuando éste sea más corto.
  const anchorDay = start.getUTCDate()
  let monthlyCount = 0

  while (current <= endDate && results.length < maxCount) {
    results.push(new Date(current))
    switch (frequency) {
      case 'daily':
        current = new Date(current.getTime() + 86400000)
        break
      case 'biweekly':
        current = new Date(current.getTime() + 2 * 86400000)
        break
      case 'weekly':
        current = new Date(current.getTime() + 7 * 86400000)
        break
      case 'bimonthly':
        current = new Date(current.getTime() + 14 * 86400000)
        break
      case 'monthly': {
        monthlyCount++
        const totalMonths = start.getUTCMonth() + monthlyCount
        const targetYear = start.getUTCFullYear() + Math.floor(totalMonths / 12)
        const targetMonth = ((totalMonths % 12) + 12) % 12
        const lastDay = new Date(Date.UTC(targetYear, targetMonth + 1, 0)).getUTCDate()
        const targetDay = Math.min(anchorDay, lastDay)
        current = new Date(Date.UTC(
          targetYear, targetMonth, targetDay,
          start.getUTCHours(), start.getUTCMinutes(), start.getUTCSeconds(),
        ))
        break
      }
    }
  }

  return results
}

/**
 * Pure helper: compute the TaskLog rows to create for one recurring task,
 * given the set of ISO dates that already have an auto-generated log.
 * Shared by generateOnCreate (single task) and generateInstancesForCouple (batch).
 */
function computeInstancesToCreate(
  task: Task,
  existingDates: Set<string>
): Prisma.TaskLogCreateManyInput[] {
  if (!task.isRecurring || !task.frequency || !task.recurrenceStart) return []

  const start = task.recurrenceStart
  const windowEnd = new Date(Date.now() + 2 * 7 * 86400000)
  const options: OccurrenceOptions = {
    endDate: task.recurrenceEnd
      ? new Date(Math.min(task.recurrenceEnd.getTime(), windowEnd.getTime()))
      : windowEnd,
  }
  if (task.maxOccurrences) {
    const remaining = task.maxOccurrences - task.occurrenceCount
    if (remaining <= 0) return []
    options.maxCount = remaining
  }

  const dates = getNextOccurrences(start, task.frequency as Frequency, 8, options)
  return dates
    .filter(d => !existingDates.has(d.toISOString()))
    .map(d => ({
      coupleId: task.coupleId,
      taskId: task.id,
      date: d,
      scheduledFor: d,
      isAutoGenerated: true,
      pointsBase: task.pointsBase,
      pointsFinal: task.pointsBase,
      status: 'pending',
    }))
}

/**
 * Generate TaskLog instances (isAutoGenerated=true) for a recurring task
 * for the next 2 weeks (reducido desde 8 en 2026-04-22: con 8 semanas un daily
 * creaba 56 placeholders que saturaban las pestañas y complicaban el "anular
 * futuras" del panel Recurrentes; con 2 semanas el cron semanal renueva antes
 * de que se agoten y el usuario ve bastante horizonte sin abrumarse).
 * Skips dates that already have an auto-generated log.
 */
export async function generateOnCreate(task: Task): Promise<void> {
  if (!task.isRecurring || !task.frequency || !task.recurrenceStart) return

  // Fetch existing auto-generated logs to avoid duplicates
  const existingLogs = await prisma.taskLog.findMany({
    where: { taskId: task.id, isAutoGenerated: true },
    select: { scheduledFor: true },
  })
  const existingDates = new Set(
    existingLogs
      .map(l => l.scheduledFor?.toISOString())
      .filter((d): d is string => d !== undefined)
  )

  const toCreate = computeInstancesToCreate(task, existingDates)
  if (toCreate.length === 0) return

  await prisma.$transaction([
    prisma.taskLog.createMany({ data: toCreate, skipDuplicates: true }),
    prisma.task.update({
      where: { id: task.id },
      data: { occurrenceCount: { increment: toCreate.length } },
    }),
  ])
}

/**
 * Extend the sliding window by one week for all recurring tasks of a couple.
 * Called by the Monday cron job.
 *
 * Batched (T8): antes hacía ~3 queries por task (findMany + createMany + update
 * vía generateOnCreate). Ahora: 2 lecturas (tasks + logs existentes de todas) y
 * una transacción con 1 createMany global + updateMany de occurrenceCount
 * agrupado por incremento.
 */
export async function generateInstancesForCouple(coupleId: string): Promise<void> {
  const tasks = await prisma.task.findMany({
    where: { coupleId, isRecurring: true, frequency: { not: null } },
  })
  if (tasks.length === 0) return

  // One read for the existing auto-generated logs of ALL the couple's recurring tasks
  const existingLogs = await prisma.taskLog.findMany({
    where: { taskId: { in: tasks.map(t => t.id) }, isAutoGenerated: true },
    select: { taskId: true, scheduledFor: true },
  })
  const existingByTask = new Map<string, Set<string>>()
  for (const log of existingLogs) {
    if (!log.scheduledFor) continue
    const set = existingByTask.get(log.taskId) ?? new Set<string>()
    set.add(log.scheduledFor.toISOString())
    existingByTask.set(log.taskId, set)
  }

  const rows: Prisma.TaskLogCreateManyInput[] = []
  const countByTask = new Map<string, number>()
  for (const task of tasks) {
    const toCreate = computeInstancesToCreate(task, existingByTask.get(task.id) ?? new Set())
    if (toCreate.length === 0) continue
    rows.push(...toCreate)
    countByTask.set(task.id, toCreate.length)
  }
  if (rows.length === 0) return

  // Group tasks by increment so occurrenceCount updates collapse into few updateMany
  const taskIdsByIncrement = new Map<number, string[]>()
  for (const [taskId, count] of countByTask) {
    const ids = taskIdsByIncrement.get(count) ?? []
    ids.push(taskId)
    taskIdsByIncrement.set(count, ids)
  }

  await prisma.$transaction([
    prisma.taskLog.createMany({ data: rows, skipDuplicates: true }),
    ...[...taskIdsByIncrement].map(([count, ids]) =>
      prisma.task.updateMany({
        where: { id: { in: ids } },
        data: { occurrenceCount: { increment: count } },
      })
    ),
  ])
}

/**
 * Run weekly generation for ALL couples with active recurring tasks.
 * Called by cron every Monday at 08:00.
 */
export async function runWeeklyGeneration(): Promise<void> {
  const couples = await prisma.couple.findMany({
    where: { tasks: { some: { isRecurring: true } } },
    select: { id: true },
  })
  for (const couple of couples) {
    await generateInstancesForCouple(couple.id).catch(err =>
      logger.error({ err }, `recurringTaskService error for couple ${couple.id}`)
    )
  }
}
