-- v1.3 La Casa: Task scheduling, ShoppingList, ShoppingItem, Todo

-- AlterTable Task: add scheduling/recurrence fields
ALTER TABLE "Task" ADD COLUMN "scheduledFor" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN "isRecurring" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Task" ADD COLUMN "frequency" TEXT;
ALTER TABLE "Task" ADD COLUMN "recurrenceStart" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN "recurrenceEnd" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN "maxOccurrences" INTEGER;
ALTER TABLE "Task" ADD COLUMN "occurrenceCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable TaskLog: add scheduling fields, drop unique constraint
ALTER TABLE "TaskLog" ADD COLUMN "scheduledFor" TIMESTAMP(3);
ALTER TABLE "TaskLog" ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TaskLog" DROP CONSTRAINT IF EXISTS "TaskLog_coupleId_taskId_date_completedBy_key";
CREATE INDEX IF NOT EXISTS "TaskLog_scheduledFor_idx" ON "TaskLog"("scheduledFor");

-- CreateTable ShoppingList
CREATE TABLE "ShoppingList" (
    "id" TEXT NOT NULL,
    "coupleId" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "archivedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ShoppingList_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "ShoppingList_coupleId_idx" ON "ShoppingList"("coupleId");
ALTER TABLE "ShoppingList" ADD CONSTRAINT "ShoppingList_coupleId_fkey"
  FOREIGN KEY ("coupleId") REFERENCES "Couple"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- CreateTable ShoppingItem
CREATE TABLE "ShoppingItem" (
    "id" TEXT NOT NULL,
    "listId" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "isChecked" BOOLEAN NOT NULL DEFAULT false,
    "checkedBy" TEXT,
    "checkedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ShoppingItem_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "ShoppingItem_listId_idx" ON "ShoppingItem"("listId");
ALTER TABLE "ShoppingItem" ADD CONSTRAINT "ShoppingItem_listId_fkey"
  FOREIGN KEY ("listId") REFERENCES "ShoppingList"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- CreateTable Todo
CREATE TABLE "Todo" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "coupleId" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "isCompleted" BOOLEAN NOT NULL DEFAULT false,
    "completedAt" TIMESTAMP(3),
    "dueDate" TIMESTAMP(3),
    "isShared" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Todo_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Todo_userId_idx" ON "Todo"("userId");
CREATE INDEX "Todo_coupleId_idx" ON "Todo"("coupleId");
ALTER TABLE "Todo" ADD CONSTRAINT "Todo_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Todo" ADD CONSTRAINT "Todo_coupleId_fkey"
  FOREIGN KEY ("coupleId") REFERENCES "Couple"("id") ON DELETE CASCADE ON UPDATE CASCADE;
